Repository deptagency/algomart, pull requests merged in 2021-11, with the labels that each got.

#11 Re-enable pretty print for development
  services/api/src/utils/logger.ts
Labels: backend

#10 [CHORE] Package Bumps
  README.md
  apps/cms/extensions/displays/pack-price/package.json
  apps/cms/extensions/interfaces/price-conversion/package.json
  apps/cms/package.json
  apps/web/next.config.js
  apps/web/package.json
  apps/web/tsconfig.json
  package-lock.json
  package.json
  packages/schemas/package.json
  services/api/package.json
Labels: dependencies

#33 Upgrade dependencies
  apps/cms/package.json
  apps/web/package.json
  package-lock.json
  package.json
  services/api/package.json
  services/api/src/utils/logger.ts
Labels: dependencies

#82 Small screen releases filter dialog
  apps/web/src/components/releases/release-filters-mobile.module.css
  apps/web/src/components/releases/release-filters-mobile.tsx
  apps/web/src/templates/releases-template.module.css
  apps/web/src/templates/releases-template.tsx
Labels: frontend
